// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpraApi.Data;

#nullable disable

namespace SimpraApi.Data.Migrations
{
    [DbContext(typeof(SimpraDbContext))]
    [Migration("20230511185953_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpraApi.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Province")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LastName", "Country");

                    b.ToTable("Staff", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "Suite 958",
                            City = "Eltonburgh",
                            Country = "Tokelau",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 513, DateTimeKind.Utc).AddTicks(5361),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1961, 1, 31, 18, 38, 40, 803, DateTimeKind.Local).AddTicks(8710),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "golda.medhurst65@yahoo.com",
                            FirstName = "Lila",
                            LastName = "Jerde",
                            Phone = "02593920767",
                            Province = "Arizona",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "Suite 382",
                            City = "Rennerhaven",
                            Country = "Svalbard & Jan Mayen",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 513, DateTimeKind.Utc).AddTicks(7812),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1983, 11, 28, 3, 15, 42, 759, DateTimeKind.Local).AddTicks(9295),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jasper.orn@yahoo.com",
                            FirstName = "Simon",
                            LastName = "Hessel",
                            Phone = "56777845347",
                            Province = "Utah",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "Apt. 705",
                            City = "Christianhaven",
                            Country = "Spain",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 513, DateTimeKind.Utc).AddTicks(8980),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1953, 7, 7, 10, 29, 41, 681, DateTimeKind.Local).AddTicks(4144),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "octavia62@yahoo.com",
                            FirstName = "Irma",
                            LastName = "Rippin",
                            Phone = "07583051385",
                            Province = "Wisconsin",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "Apt. 149",
                            City = "Santosport",
                            Country = "Guyana",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 513, DateTimeKind.Utc).AddTicks(9981),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1988, 4, 24, 17, 33, 20, 316, DateTimeKind.Local).AddTicks(5453),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin.ebert@hotmail.com",
                            FirstName = "Emanuel",
                            LastName = "Goodwin",
                            Phone = "49592807627",
                            Province = "New York",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "Apt. 953",
                            City = "Rosemaryside",
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(981),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1974, 5, 17, 21, 43, 42, 882, DateTimeKind.Local).AddTicks(6651),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "keyon28@yahoo.com",
                            FirstName = "Mindy",
                            LastName = "Weimann",
                            Phone = "36159936155",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "Suite 551",
                            City = "Wittingview",
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(1960),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1995, 2, 28, 23, 33, 12, 940, DateTimeKind.Local).AddTicks(9797),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "talon.okon80@gmail.com",
                            FirstName = "Rosalie",
                            LastName = "Sauer",
                            Phone = "28993956525",
                            Province = "Vermont",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "Apt. 734",
                            City = "Brodystad",
                            Country = "Israel",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(3044),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1979, 6, 21, 20, 43, 42, 78, DateTimeKind.Local).AddTicks(6131),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jensen_fritsch48@hotmail.com",
                            FirstName = "Norman",
                            LastName = "Ferry",
                            Phone = "61253474805",
                            Province = "Montana",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AddressLine = "Suite 341",
                            City = "South Janickville",
                            Country = "Belgium",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(4127),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(2001, 7, 26, 11, 44, 3, 110, DateTimeKind.Local).AddTicks(216),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "drew.veum7@yahoo.com",
                            FirstName = "Ismael",
                            LastName = "Franecki",
                            Phone = "35376781283",
                            Province = "Maryland",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AddressLine = "Apt. 495",
                            City = "Barrowstown",
                            Country = "Uzbekistan",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(5143),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1993, 5, 17, 8, 33, 3, 570, DateTimeKind.Local).AddTicks(444),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elnora_kuhn23@yahoo.com",
                            FirstName = "Maggie",
                            LastName = "Kutch",
                            Phone = "11541860751",
                            Province = "Missouri",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AddressLine = "Apt. 980",
                            City = "West Darrellfort",
                            Country = "Turkey",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(6111),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1972, 6, 2, 2, 37, 59, 75, DateTimeKind.Local).AddTicks(1394),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "antwon_olson@gmail.com",
                            FirstName = "Keith",
                            LastName = "Hermiston",
                            Phone = "67768189642",
                            Province = "North Carolina",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AddressLine = "Apt. 192",
                            City = "Bartonfurt",
                            Country = "Singapore",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(7136),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1983, 11, 22, 2, 12, 5, 918, DateTimeKind.Local).AddTicks(7684),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pamela9@gmail.com",
                            FirstName = "Salvatore",
                            LastName = "Cruickshank",
                            Phone = "75159480493",
                            Province = "Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AddressLine = "Suite 035",
                            City = "Meganeton",
                            Country = "Austria",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(8116),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1979, 9, 23, 17, 44, 5, 479, DateTimeKind.Local).AddTicks(972),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jorge4@hotmail.com",
                            FirstName = "Ada",
                            LastName = "Gorczany",
                            Phone = "61895856222",
                            Province = "Missouri",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AddressLine = "Suite 852",
                            City = "Hilpertfurt",
                            Country = "Brazil",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 514, DateTimeKind.Utc).AddTicks(9065),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1972, 7, 14, 14, 5, 11, 624, DateTimeKind.Local).AddTicks(8830),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "keshawn.cronin64@yahoo.com",
                            FirstName = "Kevin",
                            LastName = "Hartmann",
                            Phone = "76300989874",
                            Province = "New Hampshire",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AddressLine = "Apt. 179",
                            City = "Lake Hudsonland",
                            Country = "Syrian Arab Republic",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(31),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1964, 3, 5, 22, 54, 41, 523, DateTimeKind.Local).AddTicks(4937),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eli_greenfelder29@hotmail.com",
                            FirstName = "Harold",
                            LastName = "Johnson",
                            Phone = "17747050378",
                            Province = "Delaware",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AddressLine = "Suite 575",
                            City = "Klingview",
                            Country = "American Samoa",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(1050),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1964, 7, 2, 3, 39, 8, 616, DateTimeKind.Local).AddTicks(3594),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jamey.moen55@hotmail.com",
                            FirstName = "Guillermo",
                            LastName = "Toy",
                            Phone = "26193445153",
                            Province = "Massachusetts",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AddressLine = "Apt. 004",
                            City = "Port Wilhelmine",
                            Country = "Norway",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(1989),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1988, 8, 28, 0, 16, 5, 783, DateTimeKind.Local).AddTicks(4311),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joey_wolff17@hotmail.com",
                            FirstName = "Patrick",
                            LastName = "Schimmel",
                            Phone = "94990264983",
                            Province = "Utah",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AddressLine = "Suite 859",
                            City = "Lake Jaquelinport",
                            Country = "Latvia",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(3021),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1963, 8, 21, 7, 33, 41, 668, DateTimeKind.Local).AddTicks(873),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahsaan51@hotmail.com",
                            FirstName = "Anne",
                            LastName = "Jacobson",
                            Phone = "65569297143",
                            Province = "Vermont",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AddressLine = "Suite 564",
                            City = "Buckridgemouth",
                            Country = "Saint Kitts and Nevi",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(4025),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1990, 1, 7, 16, 18, 35, 559, DateTimeKind.Local).AddTicks(1742),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "devante_maggio@gmail.com",
                            FirstName = "Kristen",
                            LastName = "Marvin",
                            Phone = "94806122011",
                            Province = "Georgia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AddressLine = "Apt. 513",
                            City = "North Carlottamouth",
                            Country = "Luxembourg",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(4990),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1953, 7, 21, 9, 31, 40, 297, DateTimeKind.Local).AddTicks(6443),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dariana30@hotmail.com",
                            FirstName = "Luis",
                            LastName = "Boehm",
                            Phone = "53089341363",
                            Province = "Idaho",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AddressLine = "Suite 572",
                            City = "Peytonfurt",
                            Country = "Albania",
                            CreatedAt = new DateTime(2023, 5, 11, 18, 59, 53, 515, DateTimeKind.Utc).AddTicks(5936),
                            CreatedBy = "admin",
                            DateOfBirth = new DateTime(1968, 2, 22, 0, 56, 47, 493, DateTimeKind.Local).AddTicks(2305),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anabel23@hotmail.com",
                            FirstName = "Matt",
                            LastName = "Greenfelder",
                            Phone = "34575265074",
                            Province = "Virginia",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
