// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpraApi.Persistance.EntityFramework;

#nullable disable

namespace SimpraApi.Persistance.Migrations
{
    [DbContext(typeof(SimpraDbContext))]
    partial class SimpraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpraApi.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(3924),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beauty",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4369),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automotive",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4388),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computers",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4400),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Outdoors",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4408),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clothing",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4419),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grocery",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4427),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tools",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4434),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Baby",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4443),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electronics",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 411, DateTimeKind.Utc).AddTicks(4451),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Movies",
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Product", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(4362),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Soft Car",
                            Status = 1,
                            Tag = "3397256128365",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://kaylin.net"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(5434),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Soft Hat",
                            Status = 1,
                            Tag = "9385976234903",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://dominique.biz"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(5626),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Cotton Towels",
                            Status = 1,
                            Tag = "8576297255857",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://lennie.biz"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(5719),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Cotton Shoes",
                            Status = 1,
                            Tag = "4296933998880",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://stanford.net"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(5807),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Metal Sausages",
                            Status = 1,
                            Tag = "6666526365227",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://jamison.com"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(5978),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licensed Fresh Tuna",
                            Status = 1,
                            Tag = "2298615802418",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://bianka.name"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6060),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Rubber Car",
                            Status = 1,
                            Tag = "9056339729793",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://larissa.biz"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6128),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Plastic Car",
                            Status = 1,
                            Tag = "2884994063788",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://betty.com"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6194),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Concrete Cheese",
                            Status = 1,
                            Tag = "8270243350657",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://jadyn.com"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6340),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Metal Mouse",
                            Status = 1,
                            Tag = "1154888150049",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://gerda.com"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6412),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Fresh Cheese",
                            Status = 1,
                            Tag = "8149081437038",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://demetris.biz"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6485),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Metal Bike",
                            Status = 1,
                            Tag = "5036553233324",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://eryn.biz"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6559),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Soft Salad",
                            Status = 1,
                            Tag = "8124039616710",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://jamison.info"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6631),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Concrete Chicken",
                            Status = 1,
                            Tag = "2457507569642",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://magali.com"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6705),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Rubber Shirt",
                            Status = 1,
                            Tag = "6579135857574",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://verona.com"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6855),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Plastic Gloves",
                            Status = 1,
                            Tag = "0404826081326",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://elsa.net"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(6936),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Soft Fish",
                            Status = 1,
                            Tag = "7526020772534",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://wiley.com"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7010),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Granite Mouse",
                            Status = 1,
                            Tag = "9353944583100",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://jayson.net"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7084),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Metal Pizza",
                            Status = 1,
                            Tag = "4135751632791",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://agnes.com"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7159),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Fresh Keyboard",
                            Status = 1,
                            Tag = "7521621165242",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://rodolfo.info"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7246),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Plastic Chips",
                            Status = 1,
                            Tag = "2669397506526",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://jules.name"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7323),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Concrete Chicken",
                            Status = 1,
                            Tag = "3810294704525",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://lue.biz"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7466),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Steel Pizza",
                            Status = 1,
                            Tag = "9513442714899",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kade.name"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7540),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Steel Shoes",
                            Status = 1,
                            Tag = "7286931584571",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://garth.name"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7617),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Plastic Pants",
                            Status = 1,
                            Tag = "2129638855559",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://lea.name"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7734),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Frozen Fish",
                            Status = 1,
                            Tag = "2185745934266",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://angelica.name"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7808),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Soft Soap",
                            Status = 1,
                            Tag = "1022677915172",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://ımogene.com"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(7883),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Wooden Soap",
                            Status = 1,
                            Tag = "5733886097066",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://baby.info"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8057),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gorgeous Fresh Chicken",
                            Status = 1,
                            Tag = "2406010631452",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://cydney.biz"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8144),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Plastic Fish",
                            Status = 1,
                            Tag = "7837435766972",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://deondre.org"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8220),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Wooden Chips",
                            Status = 1,
                            Tag = "2366092005254",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://adell.com"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8297),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Metal Cheese",
                            Status = 1,
                            Tag = "0268273766058",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://ıgnacio.net"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8374),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Steel Computer",
                            Status = 1,
                            Tag = "6279472631355",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://archibald.biz"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8452),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Metal Car",
                            Status = 1,
                            Tag = "5335129572516",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://margarete.biz"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8525),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Cotton Ball",
                            Status = 1,
                            Tag = "3460475293135",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://gladys.com"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8713),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Granite Sausages",
                            Status = 1,
                            Tag = "8491568929629",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://viviane.org"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8795),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gorgeous Fresh Bike",
                            Status = 1,
                            Tag = "3064004553211",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://chasity.biz"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8872),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Granite Hat",
                            Status = 1,
                            Tag = "0835191505924",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://laury.biz"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(8950),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Plastic Tuna",
                            Status = 1,
                            Tag = "5649667742349",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://scarlett.info"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9027),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Granite Salad",
                            Status = 1,
                            Tag = "5560518585772",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://fritz.com"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9107),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Frozen Computer",
                            Status = 1,
                            Tag = "4827555820114",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://greta.info"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9338),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Rubber Chair",
                            Status = 1,
                            Tag = "6457580266113",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://cristina.org"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9442),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Fresh Table",
                            Status = 1,
                            Tag = "3623632357310",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://flavie.org"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9519),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gorgeous Concrete Computer",
                            Status = 1,
                            Tag = "6431031656265",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://nichole.name"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9602),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Plastic Sausages",
                            Status = 1,
                            Tag = "3140256753729",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://bartholome.net"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9682),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Plastic Salad",
                            Status = 1,
                            Tag = "7963135450924",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://lavinia.org"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9758),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Soft Tuna",
                            Status = 1,
                            Tag = "6918598608994",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://jamaal.biz"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9892),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Concrete Bike",
                            Status = 1,
                            Tag = "7698975687185",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://ashton.org"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 415, DateTimeKind.Utc).AddTicks(9983),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Plastic Computer",
                            Status = 1,
                            Tag = "4029006220553",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://dakota.name"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 5, 26, 11, 20, 53, 416, DateTimeKind.Utc).AddTicks(63),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Rubber Bike",
                            Status = 1,
                            Tag = "8665147278334",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://mina.org"
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.Product", b =>
                {
                    b.HasOne("SimpraApi.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SimpraApi.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
