// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpraApi.Persistance.EntityFramework;

#nullable disable

namespace SimpraApi.Persistance.Migrations
{
    [DbContext(typeof(SimpraDbContext))]
    [Migration("20230602163420_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpraApi.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Category", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a06c1dd-b246-4c95-a570-0edbd496a69a"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4345),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Games",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7f8c207e-2e58-48ef-a109-8aced3a0384f"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4760),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kids",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("645648a5-69ee-4494-bd3c-f7ff58e798ca"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4780),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electronics",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e0672d1b-4077-482d-98b4-e95d4aaf3a81"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4791),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Movies",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7145b74f-6789-48ea-9363-d01074fb65b5"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4800),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4810),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Industrial",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4819),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sports",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("48537adc-4408-4c6f-af02-c48e4c1762e6"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4828),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Outdoors",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e6acfc95-4ed3-4ed8-bba5-3b8dbc1afe20"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4848),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garden",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 24, DateTimeKind.Utc).AddTicks(4858),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Product", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d044ef5-8d71-47b2-8095-4a1a65e9f0a4"),
                            CategoryId = new Guid("9a06c1dd-b246-4c95-a570-0edbd496a69a"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(5627),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Granite Salad",
                            Status = "added",
                            Tag = "9576846097210",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://amos.name"
                        },
                        new
                        {
                            Id = new Guid("8c585822-143d-4bb4-b093-4867411a5464"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6221),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Frozen Hat",
                            Status = "added",
                            Tag = "1954375614173",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://alexys.org"
                        },
                        new
                        {
                            Id = new Guid("7d2a9097-f10c-4d9c-afe6-bce66434edc2"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6301),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Granite Sausages",
                            Status = "added",
                            Tag = "6414281869517",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://myrl.biz"
                        },
                        new
                        {
                            Id = new Guid("749dfe35-22e4-452d-a52a-dcaffc124d42"),
                            CategoryId = new Guid("e0672d1b-4077-482d-98b4-e95d4aaf3a81"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6357),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Plastic Bike",
                            Status = "added",
                            Tag = "2282687850385",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://melody.net"
                        },
                        new
                        {
                            Id = new Guid("4d374591-d5ee-4a95-ad43-2321bd3aeb9c"),
                            CategoryId = new Guid("e6acfc95-4ed3-4ed8-bba5-3b8dbc1afe20"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6404),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Granite Ball",
                            Status = "added",
                            Tag = "1936719722874",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://zachery.org"
                        },
                        new
                        {
                            Id = new Guid("89307360-e1d2-4bb9-9170-96e169f8954d"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6492),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Steel Mouse",
                            Status = "added",
                            Tag = "4559156554500",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://jaylen.name"
                        },
                        new
                        {
                            Id = new Guid("cc5b60fd-bed9-4cdf-aa7d-68ee5fd3512d"),
                            CategoryId = new Guid("645648a5-69ee-4494-bd3c-f7ff58e798ca"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6554),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Metal Pants",
                            Status = "added",
                            Tag = "4079254969698",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://shanie.com"
                        },
                        new
                        {
                            Id = new Guid("f720db3e-8c50-4bbe-9465-663583bb22d8"),
                            CategoryId = new Guid("48537adc-4408-4c6f-af02-c48e4c1762e6"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6603),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gorgeous Metal Towels",
                            Status = "added",
                            Tag = "7937545162654",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://hardy.name"
                        },
                        new
                        {
                            Id = new Guid("3343a58f-e897-4c04-94c3-ab2119af8f99"),
                            CategoryId = new Guid("7145b74f-6789-48ea-9363-d01074fb65b5"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6649),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Rubber Cheese",
                            Status = "added",
                            Tag = "2492864289123",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://carleton.org"
                        },
                        new
                        {
                            Id = new Guid("a7cd6192-5e1e-417d-89d2-15390a144901"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6696),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Rubber Shoes",
                            Status = "added",
                            Tag = "0698719828994",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://ubaldo.com"
                        },
                        new
                        {
                            Id = new Guid("6d454bb2-4087-427b-bfa6-90d06cf324d3"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6743),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Soft Cheese",
                            Status = "added",
                            Tag = "0906042053663",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://alphonso.name"
                        },
                        new
                        {
                            Id = new Guid("c06fead6-0f2b-4de4-bf74-d87fbdbae060"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6786),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Plastic Tuna",
                            Status = "added",
                            Tag = "9033617376535",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://adolf.net"
                        },
                        new
                        {
                            Id = new Guid("c60b4f65-4639-4fe0-851b-9e176e4df592"),
                            CategoryId = new Guid("48537adc-4408-4c6f-af02-c48e4c1762e6"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6872),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Concrete Pants",
                            Status = "added",
                            Tag = "1009670987450",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://name.com"
                        },
                        new
                        {
                            Id = new Guid("644cc614-a7d0-448c-a622-1350091b4eba"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6921),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Metal Mouse",
                            Status = "added",
                            Tag = "8597200257560",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://amie.name"
                        },
                        new
                        {
                            Id = new Guid("47733c06-0193-4c85-a9f9-a6155cf6ede9"),
                            CategoryId = new Guid("7f8c207e-2e58-48ef-a109-8aced3a0384f"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(6968),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Plastic Computer",
                            Status = "added",
                            Tag = "6410275666469",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://kira.org"
                        },
                        new
                        {
                            Id = new Guid("614d2053-1c6c-4828-b4c6-03d419cdfc4f"),
                            CategoryId = new Guid("7145b74f-6789-48ea-9363-d01074fb65b5"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7012),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Frozen Keyboard",
                            Status = "added",
                            Tag = "9526809231427",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://heidi.net"
                        },
                        new
                        {
                            Id = new Guid("1dcd8991-5627-4a7e-a0d7-35a86c823453"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7056),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Granite Keyboard",
                            Status = "added",
                            Tag = "9438709288176",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://krystina.com"
                        },
                        new
                        {
                            Id = new Guid("fbf057f7-a030-4962-a53d-50b9eb95d3b5"),
                            CategoryId = new Guid("48537adc-4408-4c6f-af02-c48e4c1762e6"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7100),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Fresh Chips",
                            Status = "added",
                            Tag = "9641799918834",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://cortney.com"
                        },
                        new
                        {
                            Id = new Guid("29e6057f-a9c3-4913-9729-73ce676a2616"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7183),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Concrete Sausages",
                            Status = "added",
                            Tag = "7190227454472",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://ashly.com"
                        },
                        new
                        {
                            Id = new Guid("aafba511-7b95-42c2-9b0a-4201cec2d8d5"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7232),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Plastic Ball",
                            Status = "added",
                            Tag = "6962729415517",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://daphne.name"
                        },
                        new
                        {
                            Id = new Guid("0e8361b2-da21-45fd-948a-1a5f718f65d5"),
                            CategoryId = new Guid("7f8c207e-2e58-48ef-a109-8aced3a0384f"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7277),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Steel Bike",
                            Status = "added",
                            Tag = "0354673901639",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://emelie.net"
                        },
                        new
                        {
                            Id = new Guid("aeacabfd-4108-4a25-9b6a-a90ef1713327"),
                            CategoryId = new Guid("645648a5-69ee-4494-bd3c-f7ff58e798ca"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7321),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Steel Towels",
                            Status = "added",
                            Tag = "4478365849750",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://dusty.net"
                        },
                        new
                        {
                            Id = new Guid("5674f136-8197-497d-a469-9899e6c1a490"),
                            CategoryId = new Guid("e6acfc95-4ed3-4ed8-bba5-3b8dbc1afe20"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7367),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Cotton Chips",
                            Status = "added",
                            Tag = "6678811509896",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://edgardo.org"
                        },
                        new
                        {
                            Id = new Guid("60fa8466-82c1-46e4-8759-748c8c3f78be"),
                            CategoryId = new Guid("645648a5-69ee-4494-bd3c-f7ff58e798ca"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7412),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Fresh Sausages",
                            Status = "added",
                            Tag = "1292933088531",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://ayden.org"
                        },
                        new
                        {
                            Id = new Guid("cd4b7a1c-f163-41a5-b851-a7d2594d02a3"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7454),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Concrete Chips",
                            Status = "added",
                            Tag = "8272757901370",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://nicklaus.net"
                        },
                        new
                        {
                            Id = new Guid("ac4cda7e-04af-472d-a8dd-b69dab9793b2"),
                            CategoryId = new Guid("e0672d1b-4077-482d-98b4-e95d4aaf3a81"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7541),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Granite Cheese",
                            Status = "added",
                            Tag = "2936020335557",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://garrett.biz"
                        },
                        new
                        {
                            Id = new Guid("24cb83ea-74f6-490e-85e6-9938541308a8"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7587),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Rubber Shirt",
                            Status = "added",
                            Tag = "2951028120714",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://luciano.biz"
                        },
                        new
                        {
                            Id = new Guid("9e03e708-ae37-49eb-afdc-43dc91c47480"),
                            CategoryId = new Guid("9a06c1dd-b246-4c95-a570-0edbd496a69a"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7630),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Soft Fish",
                            Status = "added",
                            Tag = "3893934566547",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://connor.biz"
                        },
                        new
                        {
                            Id = new Guid("b9277744-92ba-4d33-8fe2-2c2a16403371"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7675),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licensed Metal Ball",
                            Status = "added",
                            Tag = "0475262519797",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://fleta.info"
                        },
                        new
                        {
                            Id = new Guid("c0ec624a-824b-4f1a-a4d4-62e77762dcb2"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7717),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Wooden Bacon",
                            Status = "added",
                            Tag = "4913839374012",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://chanelle.name"
                        },
                        new
                        {
                            Id = new Guid("94db3fe8-5793-4e67-b023-fd93d1d20ea4"),
                            CategoryId = new Guid("7145b74f-6789-48ea-9363-d01074fb65b5"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7764),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Frozen Ball",
                            Status = "added",
                            Tag = "1935714308076",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kitty.info"
                        },
                        new
                        {
                            Id = new Guid("2dac0c77-19cd-4862-a724-113f4564528d"),
                            CategoryId = new Guid("9a06c1dd-b246-4c95-a570-0edbd496a69a"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7841),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Soft Computer",
                            Status = "added",
                            Tag = "4378780307838",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://hal.name"
                        },
                        new
                        {
                            Id = new Guid("321300f3-3cca-42dc-b707-54b1977bd852"),
                            CategoryId = new Guid("e0672d1b-4077-482d-98b4-e95d4aaf3a81"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7889),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Frozen Pizza",
                            Status = "added",
                            Tag = "7454939440261",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://hailee.info"
                        },
                        new
                        {
                            Id = new Guid("3ccdb491-e59c-4db6-bafb-73a1b78160eb"),
                            CategoryId = new Guid("48537adc-4408-4c6f-af02-c48e4c1762e6"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7934),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Rubber Hat",
                            Status = "added",
                            Tag = "2857183622721",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://katelynn.info"
                        },
                        new
                        {
                            Id = new Guid("3a84dbaa-ad67-4931-92f3-1f98730bad60"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(7978),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Wooden Tuna",
                            Status = "added",
                            Tag = "9974371990301",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://monte.info"
                        },
                        new
                        {
                            Id = new Guid("86a76497-8a4a-4f26-aad2-ffae59df0132"),
                            CategoryId = new Guid("e6acfc95-4ed3-4ed8-bba5-3b8dbc1afe20"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8022),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Steel Salad",
                            Status = "added",
                            Tag = "8204389640044",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://luella.info"
                        },
                        new
                        {
                            Id = new Guid("32a0024a-0b4f-492e-934c-3f3a5f25a6d8"),
                            CategoryId = new Guid("7f8c207e-2e58-48ef-a109-8aced3a0384f"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8066),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Metal Pants",
                            Status = "added",
                            Tag = "2222723559827",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://samson.biz"
                        },
                        new
                        {
                            Id = new Guid("02dbaf08-2bb0-4068-b3ce-ae328be96f1a"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8164),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licensed Rubber Chair",
                            Status = "added",
                            Tag = "2396343321642",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://andreanne.com"
                        },
                        new
                        {
                            Id = new Guid("bac72417-8bd2-4199-bf6f-ecdd7befded6"),
                            CategoryId = new Guid("21159e48-34b0-4312-ae46-d8d959a9f4e4"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8221),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Fresh Ball",
                            Status = "added",
                            Tag = "3110965368811",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://evert.name"
                        },
                        new
                        {
                            Id = new Guid("a6248778-fed2-4b01-b479-4de733014c6b"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8266),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Granite Ball",
                            Status = "added",
                            Tag = "2923353734065",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://leland.biz"
                        },
                        new
                        {
                            Id = new Guid("a8dad9f9-dfa3-4bc8-8eed-8f53f4fd8494"),
                            CategoryId = new Guid("48537adc-4408-4c6f-af02-c48e4c1762e6"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8308),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gorgeous Plastic Salad",
                            Status = "added",
                            Tag = "8559895909339",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://adriel.com"
                        },
                        new
                        {
                            Id = new Guid("40dcd584-b404-46d2-a4ee-1151c3a22273"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8351),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Rubber Pants",
                            Status = "added",
                            Tag = "2623108112628",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://lavern.org"
                        },
                        new
                        {
                            Id = new Guid("36ab90bb-cad4-4e1f-8b5f-b035a6e2c501"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8394),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Granite Cheese",
                            Status = "added",
                            Tag = "2233226529422",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://naomi.name"
                        },
                        new
                        {
                            Id = new Guid("23ddd884-895c-47ac-bd47-1c1e4c4e4442"),
                            CategoryId = new Guid("9a06c1dd-b246-4c95-a570-0edbd496a69a"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8436),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Fresh Car",
                            Status = "added",
                            Tag = "5606872516738",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://anita.com"
                        },
                        new
                        {
                            Id = new Guid("27f8e31a-d15a-4fd8-a83c-38f89614812d"),
                            CategoryId = new Guid("e6acfc95-4ed3-4ed8-bba5-3b8dbc1afe20"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8521),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Concrete Tuna",
                            Status = "added",
                            Tag = "1455935950262",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://eliezer.biz"
                        },
                        new
                        {
                            Id = new Guid("0cd74a8a-895f-4d9a-9c30-ff56ba053073"),
                            CategoryId = new Guid("9a06c1dd-b246-4c95-a570-0edbd496a69a"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8565),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Concrete Towels",
                            Status = "added",
                            Tag = "6880293335867",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://della.org"
                        },
                        new
                        {
                            Id = new Guid("29c3da26-ab82-4e89-94a2-811883ac830b"),
                            CategoryId = new Guid("41895378-3d39-4fe8-8533-df5fd1aa6ebb"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8613),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Rubber Chair",
                            Status = "added",
                            Tag = "4283717858935",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://flavie.name"
                        },
                        new
                        {
                            Id = new Guid("b3022b16-1c6a-4ffe-b21e-9a676e01c3e2"),
                            CategoryId = new Guid("e6acfc95-4ed3-4ed8-bba5-3b8dbc1afe20"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8655),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licensed Plastic Bike",
                            Status = "added",
                            Tag = "5130148524658",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://eloisa.com"
                        },
                        new
                        {
                            Id = new Guid("9e529494-5176-46dd-8b50-cc55d77c4a8d"),
                            CategoryId = new Guid("7145b74f-6789-48ea-9363-d01074fb65b5"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8698),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Metal Ball",
                            Status = "added",
                            Tag = "6783595889734",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://nedra.info"
                        },
                        new
                        {
                            Id = new Guid("42d7dbd4-0a92-47f4-aedf-639cf0c5e33b"),
                            CategoryId = new Guid("ce9c3933-d0fc-410e-8132-a9dc1e26a965"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 26, DateTimeKind.Utc).AddTicks(8741),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Wooden Shoes",
                            Status = "added",
                            Tag = "4098625591894",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://jaclyn.com"
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PasswordRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("User", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4df9be0-78af-4078-86b4-d1ba2919ee38"),
                            CreatedAt = new DateTime(2023, 6, 2, 16, 34, 20, 30, DateTimeKind.Utc).AddTicks(9549),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@simpra.com",
                            FirstName = "admin",
                            LastActivity = new DateTime(2023, 6, 2, 16, 34, 20, 30, DateTimeKind.Utc).AddTicks(9551),
                            LastName = "admin",
                            Password = new byte[] { 140, 105, 118, 229, 181, 65, 4, 21, 189, 233, 8, 189, 77, 238, 21, 223, 177, 103, 169, 200, 115, 252, 75, 184, 168, 31, 111, 42, 180, 72, 169, 24 },
                            PasswordRetryCount = 0,
                            Role = "admin",
                            Status = "active",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.Product", b =>
                {
                    b.HasOne("SimpraApi.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SimpraApi.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
