// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpraApi.Persistance.EntityFramework;

#nullable disable

namespace SimpraApi.Persistance.Migrations
{
    [DbContext(typeof(SimpraDbContext))]
    partial class SimpraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpraApi.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Category", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4129),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Games",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("82a5e90d-a08c-430e-a04d-df0dee8bf17e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4649),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shoes",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4668),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garden",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b3787a64-206d-40c0-a677-3852dd9f9ba3"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4680),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kids",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3434d6e3-9e09-4a0e-8cfc-db303f22bb48"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4690),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Outdoors",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ba920d3f-56a1-45f3-b9cf-9c0d0a87669e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4777),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Industrial",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c7d60216-04d6-45eb-9dce-50a247842e59"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4790),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tools",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c544090-0835-4a05-b116-a62e5eddd57f"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4800),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toys",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("36a4ff40-013b-4be3-ade7-c0aac4f2b8a4"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4809),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Books",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 937, DateTimeKind.Utc).AddTicks(4821),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sports",
                            Status = "added",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Product", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b760616-87d1-473c-bb37-43a5cb6bf1f0"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(1264),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Cotton Bike",
                            Status = "added",
                            Tag = "0665226823729",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://jamir.name"
                        },
                        new
                        {
                            Id = new Guid("f36cc540-0961-44ad-9dd3-0bbbcf90cdbb"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(1818),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Rubber Table",
                            Status = "added",
                            Tag = "5885445599976",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://tabitha.com"
                        },
                        new
                        {
                            Id = new Guid("162d35f1-31e1-47fa-9ab2-eaf8267a6ca8"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2058),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Granite Chips",
                            Status = "added",
                            Tag = "5567101835931",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://arnold.net"
                        },
                        new
                        {
                            Id = new Guid("e4bc1c8e-e730-4990-b6b2-d6398de7540d"),
                            CategoryId = new Guid("3434d6e3-9e09-4a0e-8cfc-db303f22bb48"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2117),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Steel Pants",
                            Status = "added",
                            Tag = "1031280686522",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://devyn.org"
                        },
                        new
                        {
                            Id = new Guid("be222974-26f2-4ce5-a3ba-9c5b12b74543"),
                            CategoryId = new Guid("ba920d3f-56a1-45f3-b9cf-9c0d0a87669e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2167),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Fresh Hat",
                            Status = "added",
                            Tag = "0531412637190",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://rebekah.name"
                        },
                        new
                        {
                            Id = new Guid("bd4fd02f-8a9a-4449-a75a-6a7e0b03afab"),
                            CategoryId = new Guid("b3787a64-206d-40c0-a677-3852dd9f9ba3"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2218),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Wooden Shoes",
                            Status = "added",
                            Tag = "8440962140932",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://damion.net"
                        },
                        new
                        {
                            Id = new Guid("d04e3063-1d64-4079-805a-988996d196a5"),
                            CategoryId = new Guid("c7d60216-04d6-45eb-9dce-50a247842e59"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2265),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Concrete Sausages",
                            Status = "added",
                            Tag = "2953144852401",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://lori.org"
                        },
                        new
                        {
                            Id = new Guid("7237f793-958c-4355-8467-36ce27405977"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2318),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rustic Rubber Shoes",
                            Status = "added",
                            Tag = "0584829455024",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://gaston.org"
                        },
                        new
                        {
                            Id = new Guid("3b949ed2-9106-447b-a82e-5e30c83b09d3"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2456),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Soft Fish",
                            Status = "added",
                            Tag = "8278757602187",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://collin.org"
                        },
                        new
                        {
                            Id = new Guid("8782867e-0529-4e28-b8ca-9ebf8dbd2484"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2510),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Soft Chips",
                            Status = "added",
                            Tag = "3773308626339",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://darlene.name"
                        },
                        new
                        {
                            Id = new Guid("05861dae-2ee5-4356-aac6-6b03197055e3"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2553),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Rubber Soap",
                            Status = "added",
                            Tag = "9720759112038",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://gillian.name"
                        },
                        new
                        {
                            Id = new Guid("2b8adbf5-f2b6-4a0c-ad96-ee822c45f888"),
                            CategoryId = new Guid("36a4ff40-013b-4be3-ade7-c0aac4f2b8a4"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2597),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Cotton Sausages",
                            Status = "added",
                            Tag = "1617952992858",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://brenna.info"
                        },
                        new
                        {
                            Id = new Guid("8e6b60ea-4941-428b-96f0-fec3bb438956"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2640),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Plastic Chips",
                            Status = "added",
                            Tag = "0016449091110",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://kaylah.com"
                        },
                        new
                        {
                            Id = new Guid("49c6cf29-1a28-4ce9-9338-37c43eff09b9"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2683),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gorgeous Concrete Car",
                            Status = "added",
                            Tag = "5728384315446",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://rene.com"
                        },
                        new
                        {
                            Id = new Guid("0e1ffb65-ae28-46ae-a35f-00ced8dd29f0"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2768),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Concrete Pizza",
                            Status = "added",
                            Tag = "3118809384744",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kristoffer.net"
                        },
                        new
                        {
                            Id = new Guid("153fa0aa-5cc5-450b-a064-cf5c072f2b6d"),
                            CategoryId = new Guid("3c544090-0835-4a05-b116-a62e5eddd57f"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2822),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Cotton Computer",
                            Status = "added",
                            Tag = "1657338706549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://naomi.name"
                        },
                        new
                        {
                            Id = new Guid("9d41c785-9c82-489d-939b-335b3c551455"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2867),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Wooden Bike",
                            Status = "added",
                            Tag = "5904335763157",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://elvera.net"
                        },
                        new
                        {
                            Id = new Guid("6308326f-e23c-4f5c-a6fe-733a861ad170"),
                            CategoryId = new Guid("82a5e90d-a08c-430e-a04d-df0dee8bf17e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2910),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Wooden Ball",
                            Status = "added",
                            Tag = "0551357600288",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://osvaldo.info"
                        },
                        new
                        {
                            Id = new Guid("5484e15d-2cf3-44b0-829e-a77d89838995"),
                            CategoryId = new Guid("36a4ff40-013b-4be3-ade7-c0aac4f2b8a4"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2954),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Plastic Bike",
                            Status = "added",
                            Tag = "7837489966670",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://concepcion.com"
                        },
                        new
                        {
                            Id = new Guid("e7bf459d-ed87-4806-98f9-37c3544e94c7"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(2996),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Metal Gloves",
                            Status = "added",
                            Tag = "7459911408956",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://johnpaul.org"
                        },
                        new
                        {
                            Id = new Guid("69e12d75-4ea7-4666-ba10-d1751414d19a"),
                            CategoryId = new Guid("b3787a64-206d-40c0-a677-3852dd9f9ba3"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3040),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Concrete Chips",
                            Status = "added",
                            Tag = "2455902107889",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://paris.net"
                        },
                        new
                        {
                            Id = new Guid("22230984-97d5-4ebf-8925-0e5d7854e263"),
                            CategoryId = new Guid("b3787a64-206d-40c0-a677-3852dd9f9ba3"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3127),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Fresh Shoes",
                            Status = "added",
                            Tag = "8800376689500",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://rubye.net"
                        },
                        new
                        {
                            Id = new Guid("05ac380a-9afb-408d-a466-bc557b8ff068"),
                            CategoryId = new Guid("ba920d3f-56a1-45f3-b9cf-9c0d0a87669e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3171),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incredible Metal Towels",
                            Status = "added",
                            Tag = "2149179200236",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://hermina.org"
                        },
                        new
                        {
                            Id = new Guid("13164e36-a80d-4006-9474-32026098d36f"),
                            CategoryId = new Guid("3c544090-0835-4a05-b116-a62e5eddd57f"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3221),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Rubber Table",
                            Status = "added",
                            Tag = "9550532792399",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://hillary.name"
                        },
                        new
                        {
                            Id = new Guid("e95449ee-e81f-404b-bd08-0c837e9e8226"),
                            CategoryId = new Guid("c7d60216-04d6-45eb-9dce-50a247842e59"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3263),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Cotton Chair",
                            Status = "added",
                            Tag = "0506061308883",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://trevion.net"
                        },
                        new
                        {
                            Id = new Guid("566a38ba-dc27-4cd1-b1bd-e4580f906260"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3305),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Frozen Salad",
                            Status = "added",
                            Tag = "0254524714930",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://berry.org"
                        },
                        new
                        {
                            Id = new Guid("7b310c63-754e-424e-886a-b423798822ce"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3348),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licensed Steel Computer",
                            Status = "added",
                            Tag = "7717636099171",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://clovis.com"
                        },
                        new
                        {
                            Id = new Guid("6bb3a7ef-d305-44e5-8e4e-8d76280e2143"),
                            CategoryId = new Guid("3c544090-0835-4a05-b116-a62e5eddd57f"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3432),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Plastic Chair",
                            Status = "added",
                            Tag = "5295507660702",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://brant.net"
                        },
                        new
                        {
                            Id = new Guid("06cdf3a0-8db1-4632-9a52-d00f307f76fd"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3477),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Plastic Sausages",
                            Status = "added",
                            Tag = "8940767237528",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://gabriel.biz"
                        },
                        new
                        {
                            Id = new Guid("c2b955d3-670b-43bc-93b5-a00ea7fae912"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3520),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Steel Car",
                            Status = "added",
                            Tag = "6405390806289",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://evie.com"
                        },
                        new
                        {
                            Id = new Guid("11728d5a-d461-448a-9b29-0a676bd2c785"),
                            CategoryId = new Guid("36a4ff40-013b-4be3-ade7-c0aac4f2b8a4"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3563),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Rubber Table",
                            Status = "added",
                            Tag = "4672875155961",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kay.info"
                        },
                        new
                        {
                            Id = new Guid("add0808c-1ef9-413b-9fe3-2f9e89fa5db9"),
                            CategoryId = new Guid("36a4ff40-013b-4be3-ade7-c0aac4f2b8a4"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3608),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Concrete Tuna",
                            Status = "added",
                            Tag = "7049457594376",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://elvera.biz"
                        },
                        new
                        {
                            Id = new Guid("980754e7-11eb-45fe-9c1e-45cf033bb828"),
                            CategoryId = new Guid("ba920d3f-56a1-45f3-b9cf-9c0d0a87669e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3650),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Generic Plastic Sausages",
                            Status = "added",
                            Tag = "3600004838707",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://francisca.org"
                        },
                        new
                        {
                            Id = new Guid("2f73f77e-8f3a-4573-92b1-0afa45ae7940"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3732),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Small Plastic Ball",
                            Status = "added",
                            Tag = "3231030376163",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kiarra.org"
                        },
                        new
                        {
                            Id = new Guid("e97c67bb-4e5e-42fd-84d0-1b87e1cad3e3"),
                            CategoryId = new Guid("c7d60216-04d6-45eb-9dce-50a247842e59"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3779),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Plastic Cheese",
                            Status = "added",
                            Tag = "7535127997146",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://river.org"
                        },
                        new
                        {
                            Id = new Guid("f78b03f1-87ce-46b0-b117-abc0451d3264"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3823),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handcrafted Cotton Soap",
                            Status = "added",
                            Tag = "2638520444295",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://audreanne.info"
                        },
                        new
                        {
                            Id = new Guid("e53f8890-392d-4318-b626-c584ae0068ae"),
                            CategoryId = new Guid("3c544090-0835-4a05-b116-a62e5eddd57f"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3867),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Awesome Rubber Mouse",
                            Status = "added",
                            Tag = "2524673101522",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kaylie.org"
                        },
                        new
                        {
                            Id = new Guid("2b01e0bb-8e7f-4e1f-8076-c71d6e9a48dd"),
                            CategoryId = new Guid("3434d6e3-9e09-4a0e-8cfc-db303f22bb48"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3910),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Wooden Towels",
                            Status = "added",
                            Tag = "5995063525506",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://abbigail.info"
                        },
                        new
                        {
                            Id = new Guid("e6acc83f-e50a-449a-92fa-b99acf25c556"),
                            CategoryId = new Guid("82a5e90d-a08c-430e-a04d-df0dee8bf17e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(3953),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sleek Cotton Pants",
                            Status = "added",
                            Tag = "4331135388005",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://kip.info"
                        },
                        new
                        {
                            Id = new Guid("cd2bf314-610b-42df-96d4-a2806a006ff5"),
                            CategoryId = new Guid("82a5e90d-a08c-430e-a04d-df0dee8bf17e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4002),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Granite Shoes",
                            Status = "added",
                            Tag = "5067489769694",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://alaina.biz"
                        },
                        new
                        {
                            Id = new Guid("558913a5-80ed-4586-a66b-72965d634f03"),
                            CategoryId = new Guid("155d034b-7971-4b00-b06f-e6b25fb6308b"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4112),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Concrete Keyboard",
                            Status = "added",
                            Tag = "0787817778154",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://emily.org"
                        },
                        new
                        {
                            Id = new Guid("c4d2a232-318c-4cf8-a20f-f1288ffd0750"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4158),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Practical Frozen Chicken",
                            Status = "added",
                            Tag = "4387879413565",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://everette.net"
                        },
                        new
                        {
                            Id = new Guid("71a6f34a-9031-46fd-9906-d5b892b219c5"),
                            CategoryId = new Guid("ba920d3f-56a1-45f3-b9cf-9c0d0a87669e"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4201),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ergonomic Metal Keyboard",
                            Status = "added",
                            Tag = "9830406819019",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://hope.name"
                        },
                        new
                        {
                            Id = new Guid("f02847f8-c718-4851-9420-c0c6ecf52c22"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4243),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licensed Concrete Hat",
                            Status = "added",
                            Tag = "7189905579262",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://darius.info"
                        },
                        new
                        {
                            Id = new Guid("862c20b1-1a27-4292-9f89-0cb6ed8219e0"),
                            CategoryId = new Guid("c7d60216-04d6-45eb-9dce-50a247842e59"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4286),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tasty Frozen Ball",
                            Status = "added",
                            Tag = "8287777821164",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://rossie.info"
                        },
                        new
                        {
                            Id = new Guid("0d3adc1a-3a15-4ae4-9bdb-93ef41b1d058"),
                            CategoryId = new Guid("36a4ff40-013b-4be3-ade7-c0aac4f2b8a4"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4327),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refined Steel Hat",
                            Status = "added",
                            Tag = "1385410514606",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://ahmed.net"
                        },
                        new
                        {
                            Id = new Guid("af67e60e-9493-4b12-b958-8402995c46d3"),
                            CategoryId = new Guid("b32b9929-605a-4019-b03d-46c783fb3837"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4410),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Intelligent Concrete Salad",
                            Status = "added",
                            Tag = "2840361702025",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://eliseo.net"
                        },
                        new
                        {
                            Id = new Guid("e3437493-8bcc-4602-b11d-9991a07c8bff"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4459),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Unbranded Frozen Soap",
                            Status = "added",
                            Tag = "8368232074056",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://phoebe.info"
                        },
                        new
                        {
                            Id = new Guid("6f383a40-19eb-4d1f-8a33-2b4517b3b99e"),
                            CategoryId = new Guid("c7d60216-04d6-45eb-9dce-50a247842e59"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4504),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantastic Metal Salad",
                            Status = "added",
                            Tag = "9584309446536",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "http://turner.com"
                        },
                        new
                        {
                            Id = new Guid("186084da-a820-47ee-8ed4-06a2de2d21ad"),
                            CategoryId = new Guid("07b9025b-0dc2-4a0f-b7ed-dba4649cd1c0"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 940, DateTimeKind.Utc).AddTicks(4551),
                            CreatedBy = "admin",
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Handmade Rubber Chips",
                            Status = "added",
                            Tag = "2712850646137",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://celestine.biz"
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PasswordRetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("User", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2429a8a-a58c-4f0b-9874-ae9c8b6ba1ed"),
                            CreatedAt = new DateTime(2023, 6, 1, 11, 0, 38, 944, DateTimeKind.Utc).AddTicks(9783),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@simpra.com",
                            FirstName = "admin",
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "admin",
                            Password = new byte[] { 140, 105, 118, 229, 181, 65, 4, 21, 189, 233, 8, 189, 77, 238, 21, 223, 177, 103, 169, 200, 115, 252, 75, 184, 168, 31, 111, 42, 180, 72, 169, 24 },
                            PasswordRetryCount = 0,
                            Role = "admin",
                            Status = "active",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SimpraApi.Domain.Product", b =>
                {
                    b.HasOne("SimpraApi.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SimpraApi.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
